config/routes.rb
Rails.application.routes.draw do

  # Home Page
  root 'dangerous#landing_page'

  # User Routes

  get 'add_user' => 'users#add_user'
  get 'manage_user' => 'users#manage_user'
  get 'delete_user' => 'users#delete_user'
  patch 'manage_user' => 'users#edit_user'
  get 'manage_user_roles' => 'users#manage_roles'
  patch 'update_user_roles' => 'users#update_user_roles'

  # Resources
  resources :users
  resources :stocks
  resources :portfolios

  # path used by Register button
  post 'register_user' => 'users#create'

  # Session Routes
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get 'invalid_login' => 'dangerous#landing_page'

  # Portfolio Routes

  get 'portfolio' => 'portfolios#load'
  get 'position_history' => 'portfolios#position_history'
  get 'portfolio_history' => 'portfolios#portfolio_history'

  # Stock Routes

  get 'add_stock' => 'stocks#add_stock'
  get 'update_stock' => 'stocks#update_stock'
  post 'create_stock' => 'stocks#create'
  patch 'update_stock' => 'stocks#edit_stock'


  # Admin Routes

  get 'admin' => 'admin#manage_users'
  get 'manage_users' => 'admin#manage_users'
  get 'manage_stocks' => 'admin#manage_stocks'
  post 'admin_import' => 'admin#import'

  # Exchange Routes

  get 'exchange' => 'exchange#view'
  get 'create_trade' => 'exchange#create_trade'
  post 'create_trade' => 'exchange#execute_trade'
  post 'refresh_exchange' => 'exchange#refresh'


end

app/controllers/exchange_controller.rb
# Created by Thomas Shallenberger 3/17
# Purpose: Provide implementation for Exchange page to allow
# users to create trades affecting or creating positions in their
# portfolios. 


Quandl::ApiConfig.api_key = 'xNSxrMU_zRKHVD-7TKxJ'
Quandl::ApiConfig.api_version = '2015-04-09'

require 'open-uri'
require 'zip'

class ExchangeController < ApplicationController

	def view
		@stocks = Stock
			.where.not(stock_name: '', industry: '', sector: '', price_update: nil, stock_price: nil)
			.pluck(:id, :stock_name, :sector, :industry, :stock_symbol, :stock_price, :price_update)
			
		@headers = ['Company Name', "Sector", "Industry", "Symbol", "Price", "Last Updated", "Actions"]
		@attribs = ['stock_name', 'stock_symbol', 'stock_price']


		respond_to do |format|
			format.html {}
		end
	end

	def import
		

	end

	def refresh

		rowarray = Array.new    
    	myfile = params[:file]

    	csv = CSV.read(myfile.path)

		
		
		csv.each do |first, sec|
			name = sec.split("(", 2).first
			sym = first.split("/", 2).last
			Rails.logger.info(sym + " : " + name)

			if !Stock.exists?(:stock_symbol => sym) then
				stock = Stock.new(stock_symbol: sym, stock_name: name, stock_price: 0)
				stock.save
			elsif Stock.find_by(stock_symbol: sym).stock_price == 0
				dataset = Quandl::Dataset.get(first)
				latest = dataset.newest_available_date
				price = dataset.data(params: {start_date: latest, column_index:4}).values[0].close
				Stock.find_by(stock_symbol: sym).update_column("stock_price", price)
			end



		end
		redirect_to exchange_path
	end

	def create_trade 
		# Get all stocks, portfolio ID, user info, etc. 
		@trade = Trade.new
		@stocks = Stock.all
		Rails.logger.info(session)
		respond_to do |format|
			format.js {}
		end
	end

	def execute_trade

		Rails.logger.info(trade_params)

		# Find all the records needed for this trade. 

		@error = "NONE"

		stock = Stock.find(params[:trade][:stock_id])

		portfolio = Portfolio.find_by(user_id: session[:user_id])

		trade_type = TradeType.find(params[:trade][:trade_type])

		# Check if the position exists, in case we need to create a new one. 
		if (Position.exists?(:portfolio_id => portfolio.id, :stock_id => stock.id)) then
			position = Position.find_by(portfolio_id: portfolio.id, stock_id: stock.id)
		elsif trade_type.trade_type_name != "SELL" then
			position = Position.new(portfolio_id: portfolio.id, stock_id: stock.id, position_amount: 0)
		else
			# Tried to sell shares we don't have. 

			@error = "Position does not exist."
			Rails.logger.info(@error)
			respond_to do |format|
				format.js {}
			end
		end

		
		params[:trade][:trade_datetime] = DateTime.current
		# Check if we're using market price or queueing a trade. 
		if params[:price] == "true" then
			params[:trade][:trade_price] = stock.stock_price
		end



		trade = Trade.new(trade_params)
		
		# Modify the positions accordingly



		if trade_type.trade_type_name == "BUY" then
			# We need more checks here to make sure shit doesn't break

			if (stock.stock_price * trade_params[:trade_amount].to_d) < portfolio.portfolio_cash_account then
				Rails.logger.info(portfolio.total_value)
				Rails.logger.info(position)
				position.position_amount += trade_params[:trade_amount].to_d

				portfolio.portfolio_cash_account -= (stock.stock_price * trade_params[:trade_amount].to_d)
				Rails.logger.info(portfolio.total_value)
			else
				# Can't afford the trade. what do
				@error = "Not enough funds for this trade."
				respond_to do |format|
					format.js {}
				end
			end

			
		elsif trade_type.trade_type_name == "SELL" then

			if (trade_params[:trade_amount].to_d <= position.position_amount) then
				Rails.logger.info(portfolio.total_value)
				portfolio.portfolio_cash_account += (trade_params[:trade_amount].to_d * stock.stock_price)
				position.position_amount -= trade_params[:trade_amount].to_d
				Rails.logger.info(portfolio.total_value)
			else
				# Not enough shares to sell. 
				@error = "Not enough shares to cover this trade."
				 respond_to do |format|
					format.js {}
				end
			end
		else
		end

		if @error == "NONE"
			position.save
			trade.position_id = position.id
			trade.save
			portfolio.save
		end


		respond_to do |format|
			format.js {}
		end
	end

	private 
		def trade_params
			params.require(:trade).permit(
				:position_id,
				:stock_id,
				:trade_type,
				:trade_price,
				:trade_amount,
				:trade_datetime
			)	
		end
end

app/helpers/exchange_helper.rb
module ExchangeHelper
end

app/views/exchange/_create_trade.html.erb
  <div id="createTrade" class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 id="modalHeader" class="center">Create Trade</h4>
      </div>
      <!-- @all_attribs and @header_attribs -->
      <div class="modal-body center">
        <%= form_for @trade, url: create_trade_path, remote: true do |f| %>
          <table id='tradeTable' align="center" class="modal-table table table-striped table-bordered">
            <tbody class="center">
              <tr>
                <td class='header-td'>Stock</td>
                <td>
                  <%= f.collection_select(:stock_id, Stock.all, :id, :stock_symbol, {}, {class: "select-class"}) %>
                </td>
              </tr>
              <tr>
                <td class='header-td'>Trade Type</td>
                <td>
                  <%= f.collection_select(:trade_type, TradeType.all, :id, :trade_type_name, {}, {class: "select-class"}) %>
                </td>
              </tr>
              <tr>
                <td class='header-td'>Buy Price</td>
                <td>
                  Market Price:
                  <input type="radio" name="price" value="true" checked="true"><br>
                  Limit: 
                  <input id="limitPrice" type="radio" name="price" value="false"><br>
                  <input type="text", id="tradePrice", disabled="true">
                </td>
              </tr>
              <tr>
                <td class='header-td'>Trade Amount (Shares)</td>
                <td>
                  <%= f.text_field :trade_amount, :required => true%>
                </td>
              </tr>
            </tbody>
          </table>
          <%= f.hidden_field :position_id %>
          <%= f.hidden_field :trade_price %>
          <%= f.hidden_field :trade_datetime %>
          <%= f.submit "Execute Trade", :id => "createTradeBtn", class: "btn btn-primary center" %> 
        <% end %>
      </div>
    </div>
  </div>

app/views/exchange/_sidebar.html.erb
<div class="sidebar">
	<ul class="nav nav-pills nav-stacked">
		<li> <%= link_to 'Create Trade', create_trade_path, :remote => true %> </li>
	</ul>
</div>

app/views/exchange/create_trade.js.erb
$("#modal-window").html("<%= escape_javascript render(:partial => '/exchange/create_trade') %>");
$('#modal-window').modal('show');

$(".button-submit").on('click', function() {
	$("#modal-window").modal('hide');
})

$('.modal ').insertAfter($('body'));

$(document).ready(function() {
  $(".select-class").select2();
});

$("input[name='price']").change( function(){
	if ($("#limitPrice").prop("checked")) {$("#tradePrice").attr("disabled", false); }
	else {  $("#tradePrice").attr("disabled", true); }

});

app/views/exchange/execute_trade.js.erb
<% if @error == "NONE" then %>
	$('#modal-window').modal('hide');
	location.reload()
<% else %>
	// Display error here. 
	console.log("<%= @error %>")
<% end %>

app/views/exchange/view.html.erb
<% content_for :sidebar do %>
<!-- sidebar content -->

<% end %>

<div class="exchange">
	<h1>Exchange</h1>
	<h3>Trade stocks here.</h3>

	<table class="table table-line">
		<tbody><tr><td></td></tr></tbody>
	</table>

	<%= link_to create_trade_path, :remote => true, class: 'btn btn-primary btn-add-user' do %>
		 <span class="glyphicon"></span>
		 Create Order
	<% end %>
<!--  -->
	

	<table class="table table-bordered table-datatable">
		<thead>
			<tr>
				<% @headers.each do | header | %>
					<td>
						<%= header %>
					</td>
				<% end %>
			</tr>
		</thead>
		<tbody>
			<% @stocks.each do |stock| %>
				<tr id="<%=	stock[0] %>">
					<td><%=	stock[1] %></td>
					<td><%= stock[2] %></td>
					<td><%= stock[3] %></td>
					<td>
						<%= link_to stocks_path(:stock_symbol => stock[4]) do %>
							<span><%= stock[4] %></span>
						<% end %>
					</td>
					<td><%=	number_to_currency(stock[5]) %></td>
					<td><%= stock[6] %></td>
					<td>
						<div class="center">
							<%= link_to create_trade_path(:stock_id => stock[0]), :remote => true, class: 'btn btn-primary' do %>
								<span>Trade</span>
							<% end %>
						</div>
					</td>
				</tr>
			<% end	%>
		</tbody>
	</table>
</div>

<script type="text/javascript">
	var dataTable = $('.table-datatable').DataTable();

	document.addEventListener("turbolinks:before-cache", function() {
	  if (dataTable !== null) {
	   dataTable.destroy();
	   dataTable = null;
	  }
	});
</script>