config/routes.rb
Rails.application.routes.draw do

  # Home Page
  root 'dangerous#landing_page'

  # User Routes

  get 'add_user' => 'users#add_user'
  get 'manage_user' => 'users#manage_user'
  get 'delete_user' => 'users#delete_user'
  patch 'manage_user' => 'users#edit_user'
  get 'manage_user_roles' => 'users#manage_roles'
  patch 'update_user_roles' => 'users#update_user_roles'

  # Resources
  resources :users
  resources :stocks
  resources :portfolios

  # path used by Register button
  post 'register_user' => 'users#create'

  # Session Routes
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get 'invalid_login' => 'dangerous#landing_page'

  # Portfolio Routes

  get 'portfolio' => 'portfolios#load'
  get 'position_history' => 'portfolios#position_history'
  get 'portfolio_history' => 'portfolios#portfolio_history'

  # Stock Routes

  get 'add_stock' => 'stocks#add_stock'
  get 'update_stock' => 'stocks#update_stock'
  post 'create_stock' => 'stocks#create'
  patch 'update_stock' => 'stocks#edit_stock'


  # Admin Routes

  get 'admin' => 'admin#manage_users'
  get 'manage_users' => 'admin#manage_users'
  get 'manage_stocks' => 'admin#manage_stocks'
  post 'admin_import' => 'admin#import'

  # Exchange Routes

  get 'exchange' => 'exchange#view'
  get 'create_trade' => 'exchange#create_trade'
  post 'create_trade' => 'exchange#execute_trade'
  post 'refresh_exchange' => 'exchange#refresh'


end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	def stock_value
		stock_val = 0
		Position.where(portfolio_id: self.id).each do |position|
			stock = Stock.find(position.stock_id)
			stock_val += (position.position_amount * stock.stock_price)
		end

		return stock_val
	end

	def total_value
		total = self.stock_value
		return total + self.portfolio_cash_account
	end
end

app/models/position.rb
class Position < ActiveRecord::Base
	def value
		stock = Stock.find(self.stock_id)
		return self.position_amount * stock.stock_price
	end
end

app/models/role.rb
class Role < ActiveRecord::Base

	validates :role_name, uniqueness: true

end

app/models/stock.rb
class Stock < ActiveRecord::Base
	def to_param
		stock_symbol
	end

	def update_price(price)
		self.stock_price = price
		puts price
	end
end

app/models/trade.rb
class Trade < ActiveRecord::Base
	def type
		return TradeType.find(self.trade_type).trade_type_name
	end

	def current_price
		return Stock.find(self.stock_id).stock_price
	end

	def change
		current_price = self.current_price
		change = self.trade_price - current_price
		return change
	end
end

app/models/trade_type.rb
class TradeType < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :user_name, uniqueness: true
	validates :email, uniqueness: true
	def add_role(role)
		# Create UTR 
		Rails.logger.info("SELF: " + self.id.to_s)
		Rails.logger.info("ROLE: " + role.id.to_s)
		UserToRole.create(user_id: self.id, role_id: role.id)
	end

	def has_role(role)
		return UserToRole.exists?(:user_id => self.id, :role_id => role.id)
	end

	def is_admin
		return true
	end

	def to_param
		user_name
	end
end

app/models/user_to_role.rb
class UserToRole < ActiveRecord::Base

end

app/controllers/admin_controller.rb
# Controller for admin capabilities and dashboard


class AdminController < ApplicationController

	def dashboard

		respond_to do |format|
			format.html {}
		end

	end

	# Controller methods for routing to admin pages 
	# used to manage settings for models
	def manage_users
		@users = User.all

		respond_to do |format|
			format.html {}
		end
	end

	def import

		rowarray = Array.new    
    	myfile = params[:file]

    	csv = CSV.read(myfile.path)

		
		
		csv.each do |first, sec|
			name = sec.split("(", 2).first
			sym = first.split("/", 2).last
			Rails.logger.info(sym + " : " + name)

			if !Stock.exists?(:stock_symbol => sym) then
				stock = Stock.new(stock_symbol: sym, stock_name: name, stock_price: 0)
				stock.save
			elsif Stock.find_by(stock_symbol: sym).stock_price == 0
				dataset = Quandl::Dataset.get(first)
				latest = dataset.newest_available_date
				price = dataset.data(params: {start_date: latest, column_index:4}).values[0].close
				Stock.find_by(stock_symbol: sym).update_column("stock_price", price)
			end



		end
		redirect_to exchange_path
	end


	def manage_roles
	end

	def manage_stocks
		@stocks = Stock.all
		@headers = ['Company Name', "Symbol", "Price", "Last Updated", "Actions"]
		@attribs = ['stock_name', 'stock_symbol', 'stock_price']

		respond_to do |format|
			format.html {}
		end
	end

	def manage_portfolios
	end

	


end

app/controllers/roles_controller.rb
# Created by: Thomas Shallenberger 3/8/2017
# Purpose: Implement Role specific controller methods


class RolesController < ApplicationController
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		# Profile page
		Rails.logger.info(params)
		@current_user = User.find(session[:user_id])
		if @user = User.find_by(user_name: params[:id]) then
			
			@is_admin = @current_user.is_admin
			@is_current_user = (@user.id == @current_user.id)
			@header_attribs = ['Username', 'Email', 'New Password']
			@all_attribs = ['user_name', 'email', 'password']
			

			# Find Portfolio for User


			@portfolio = Portfolio.find_by(user_id: @user.id)
		    @position_ids = Position.where(portfolio_id: @portfolio.id).select("id")
	    	@trades = Trade.where(position_id: @position_ids)
		else
			redirect_to user_path(:id => @current_user.user_name)
		end
		

		respond_to do |format|
			format.html {}
		end
	end

	def create
		@user = User.new(user_params)

		Rails.logger.info(@user)
		if @user.save
			# TODO: cache the user id for the session. 
			session[:user_id] = @user.id
			if params[:role] then
				@user.add_role(Role.find(params[:role]))
			else
				@user.add_role(Role.find_by(role_name: "ADMIN"))
			end
			
			Portfolio.create(portfolio_name: 'Portfolio', user_id: @user.id, portfolio_cash_account: 100000.00)
			# Need a logged-in landing page. 
			redirect_to user_path(:id => @user.user_name)
		else
			# Unsuccessful login. 
			Rails.logger.info(@user.errors.full_messages)

		end

		respond_to do |format|
			format.js {}
		end
	end

	def manage_user
		@user = User.find_by(user_name: params[:user_name])
		@header_attribs = ['Username', 'Email', 'New Password']
		@all_attribs = ['user_name', 'email', 'password']

		respond_to do |format|

			format.js {}

		end
	end

	def edit_user
		Rails.logger.info(user_params)
		@user = User.find(params[:user][:id])
		@user.update_attributes(user_params)

		respond_to do |format|
			format.js {}
		end
	end

	def manage_roles
		@user = User.find_by(user_name: params[:user_name])
		@roles = Role.all
		@user_roles_bool = [];
		@roles.each do |role|
			@user_roles_bool.push(@user.has_role(role))
		end

		@user_roles = @roles.zip(@user_roles_bool)

		Rails.logger.info(@user_roles)
		
		respond_to do |format|
			format.js {}
		end
	end

	def update_user_roles
		# params[:role_check] is the array of enabled roles. 
		role_checks = params[:role_check]

		if role_checks.empty? then
		else
			UserToRole.where(:user_id => params[:user_id]).destroy_all
			role_checks.each do |role_id|
				UserToRole.create(user_id: params[:user_id], role_id: role_id)
			end
		end
		respond_to do |format|
			format.js {}
		end

	end

	def update
	end

	# method to delete user. 
	def delete
		# How does the user id get here?

		User.find(params[:id]).destroy
		
	end

	def delete_user
		# delete the user, reload the table
		Rails.logger.debug(params[:user_name])
		User.find_by(user_name: params[:user_name]).destroy()
		respond_to do |format|
			format.js {}
		end
	end

	# launch modal for adding user. 
	def add_user
		@user = User.new 
		@header_attribs = ['Username', 'Email', 'Password']
		@all_attribs = ['user_name', 'email', 'password']
		respond_to do |format| 
			format.js {}
		end
	end


	private
		# Require/permit user_name|email|password for initial registration
		def user_params
			params.require(:user).permit(
				:id,
				:user_name, 
				:email,
				:password)
		end

	
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dangerous_helper.rb
module DangerousHelper
end

app/helpers/exchange_helper.rb
module ExchangeHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard.html.erb
<% content_for :sidebar do %>
<!-- sidebar content -->
	<%= render :partial => "layouts/sidebar" %>
<% end %>

<h1>Admin Dashboard</h1>
<h2>This will actually first go to Manage Users. </h2>

app/views/admin/delete_user.js.erb
location.reload()
console.log("reload")

app/views/admin/manage_stocks.html.erb
<!-- Page for managing Users.  -->

<% content_for :sidebar do %>
<!-- sidebar content -->
	<%= render :partial => "layouts/sidebar" %>
<% end %>

<div class="manageStocks">
	<h1>Stocks</h1>
	<h3>Manage stocks here.</h3>

	<table class="table table-line">
		<tbody><tr><td></td></tr></tbody>
	</table>



	<%= form_tag({:action => :import}, multipart: true) do %>
		<table class='table table-bordered center'>
			<tbody>
				<tr>
					<td><%= file_field_tag :file %></td>
					<td><%= submit_tag( "Upload Symbols/Names", { class: 'btn btn-primary' })%></td>
				</tr>
			</tbody>
		</table>
  	<% end %>
  	
</div>

app/views/admin/manage_users.html.erb
<!-- Page for managing Users.  -->

<% content_for :sidebar do %>
<!-- sidebar content -->
	<%= render :partial => "layouts/sidebar" %>
<% end %>

<div class="manageUser">
	<h1>Users</h1>
	<h3>Manage users here.</h3>

	<table class="table table-line">
		<tbody><tr><td></td></tr></tbody>
	</table>

	<%= link_to add_user_path, :remote => true, class: 'btn btn-primary btn-add-user' do %>
		 <span class="glyphicon"></span>
		 Add User
	<% end %>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Status</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
				<tr id="<%=	user.user_name %>">
					<td><%= link_to user.user_name, portfolio_path(:id => user.user_name) %> </td>
					<td><%=	user.email %></td>
					<td>Active</td>
					<td>
						<div class="center">

							<%= link_to manage_user_path(:user_name => user.user_name), :remote => true, class: 'btn btn-default' do %>
								 <span class="glyphicon glyphicon-cog"></span>
								 Manage
							<% end %>
							<%= link_to delete_user_path(:user_name => user.user_name), :remote => true, class: 'btn btn-danger' do %>
								 <span class="glyphicon glyphicon-remove"></span>
								 Remove User
							<% end %>
							<%= link_to manage_user_roles_path(:user_name => user.user_name), :remote => true, class: 'btn btn-default' do %>
								 <span class="glyphicon glyphicon-cog"></span>
								 Roles
							<% end %>
						</div>
					</td>
				</tr>
			<% end	%>
		</tbody>
	</table>
</div>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
	<ul class="nav nav-pills nav-stacked">

		<li> <%= link_to 'Manage Users', manage_users_path %> </li>
		<li> <%= link_to 'Manage Stocks', manage_stocks_path %> </li>


	</ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>Nvestr</title>



	<!-- Can't just include all javascripts...I can include all stylesheets tho -->
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

	<!-- Add application-specific javascript here. jquery and such.  -->
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<!-- Again, no idea what this does.  -->
	<%= csrf_meta_tags %>

  <script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet"> 

  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />

  <link href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" rel="stylesheet">



  </head>
  <body>


    <%= yield :javascript %>

    <div>
      <% if user_is_logged_in? then %>
        <% if is_admin then %>
          <%= render :partial => "users/adminnavbar" %>
        <% else %>
          <%= render :partial => "users/usernavbar" %>
        <% end %>
      <% else %>
            <%= render :partial => "dangerous/dangerousnavbar" %> 
      <% end %>
    </div>
      <div class="row">
        <% if user_is_logged_in? then %>
        <div class="col-sm-2">
          <%= yield :sidebar %>
        </div>
        <div class="col-sm-8">
          <%= yield %>
        </div>
        <div class="col-sm-2"></div>
      </div>
      <% else %>

          <div class="col-sm-12">
            <%= yield :header %>
          </div>

          <div class="col-sm-2"></div>
          <div class="col-sm-8 site-content-margin">
            <!-- Site content within 8 columns.  -->
              <%= yield %>
          </div>
          <div class="col-sm-2"></div>

      <% end %>


      
    </div>
  </body>
  <!-- Modal to be used by all apps, added AFTER body -->
  <div id="modal-window" class="modal fade"></div>
</html>