config/routes.rb
Rails.application.routes.draw do

  # Home Page
  root 'dangerous#landing_page'

  # User Routes

  get 'add_user' => 'users#add_user'
  get 'manage_user' => 'users#manage_user'
  get 'delete_user' => 'users#delete_user'
  patch 'manage_user' => 'users#edit_user'
  get 'manage_user_roles' => 'users#manage_roles'
  patch 'update_user_roles' => 'users#update_user_roles'

  # Resources
  resources :users
  resources :stocks
  resources :portfolios

  # path used by Register button
  post 'register_user' => 'users#create'

  # Session Routes
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get 'invalid_login' => 'dangerous#landing_page'

  # Portfolio Routes

  get 'portfolio' => 'portfolios#load'
  get 'position_history' => 'portfolios#position_history'
  get 'portfolio_history' => 'portfolios#portfolio_history'

  # Stock Routes

  get 'add_stock' => 'stocks#add_stock'
  get 'update_stock' => 'stocks#update_stock'
  post 'create_stock' => 'stocks#create'
  patch 'update_stock' => 'stocks#edit_stock'


  # Admin Routes

  get 'admin' => 'admin#manage_users'
  get 'manage_users' => 'admin#manage_users'
  get 'manage_stocks' => 'admin#manage_stocks'
  post 'admin_import' => 'admin#import'

  # Exchange Routes

  get 'exchange' => 'exchange#view'
  get 'create_trade' => 'exchange#create_trade'
  post 'create_trade' => 'exchange#execute_trade'
  post 'refresh_exchange' => 'exchange#refresh'


end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	def stock_value
		stock_val = 0
		Position.where(portfolio_id: self.id).each do |position|
			stock = Stock.find(position.stock_id)
			stock_val += (position.position_amount * stock.stock_price)
		end

		return stock_val
	end

	def total_value
		total = self.stock_value
		return total + self.portfolio_cash_account
	end
end

app/controllers/portfolios_controller.rb
# Portfolio Controller
# 


class PortfoliosController < ApplicationController

  
  # Load
  # Should have access to a user ID in the session data.
  

  def position_history
    @position = Position.find(params[:position_id])
    @trades = Trade.where(position_id: @position.id)

    respond_to do |format|

      format.js {}

    end
  end

  def portfolio_history
    @portfolio = Portfolio.find(params[:portfolio_id])
    @position_ids = Position.where(portfolio_id: @portfolio.id).select("id")
    @trades = Trade.where(position_id: @position_ids)

    respond_to do |format|
      format.js {}
    end
  end

  def save_position

  end

  def show
    @user = User.find_by(user_name: params[:id])
    @current_user = User.find(session[:user_id])
    @portfolio = Portfolio.find_by(user_id: @user.id)
    @positions = Position.where(portfolio_id: @portfolio.id)
    @position_ids = Position.where(portfolio_id: @portfolio.id).select("id")
    @trades = Trade.where(position_id: @position_ids)
    @stocks = []
    @positions.each do |pos|
      @stocks << Stock.find(pos.stock_id)
    end
    @position_stock = @positions.zip(@stocks)
   @headers = ['Company Name', "Sector", "Industry", "Symbol", "Price", "Amount", "Value","Actions"]


    respond_to do |format|
      format.html { render :template => 'portfolios/load'}
    end

  end
  
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_portfolio_history.html.erb
  <div id="updatePosition" class="modal-dialog" style="height:300px;">
    <div class="modal-content" style="position:relative;">
      <div class="modal-header">
        <h4 id="modalHeader" class="center">Trade Activity</h4>
      </div>
      <!-- @all_attribs and @header_attribs -->
      <div class="modal-body" style="max-height:100%; overflow:auto;">
        
          <table align="center" class="table table-striped table-bordered table-headers-bold center">
            <thead>
              <tr>
                <td>Transaction</td>
                <td>Amount</td>
                <td>Price</td>
                <td>Date</td>
                <td>Current Price</td>
                <td>Change (%)</td>
              </tr>
            </thead>
            <tbody class="center">
              <% @trades.each do |trade| %>
                <tr>
                  <td><%= trade.type %></td>
                  <td><%= trade.trade_amount %></td>
                  <td><%= number_to_currency(trade.trade_price) %></td>
                  <td><%= trade.trade_datetime %></td>
                  <td><%= number_to_currency(trade.current_price) %></td>
                  <td><%= trade.change %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>

app/views/portfolios/_position_history.html.erb
  <div id="updatePosition" class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 id="modalHeader" class="center">Trade Activity</h4>
      </div>
      <!-- @all_attribs and @header_attribs -->
      <div class="modal-body">
        
          <table align="center" class="table table-striped table-bordered table-headers-bold center">
            <thead>
              <tr>
                <td>Transaction</td>
                <td>Amount</td>
                <td>Price</td>
                <td>Date</td>
                <td>Current Price</td>
                <td>Change (%)</td>
              </tr>
            </thead>
            <tbody class="center">
              <% @trades.each do |trade| %>
                <tr>
                  <td><%= trade.type %></td>
                  <td><%= trade.trade_amount %></td>
                  <td><%= number_to_currency(trade.trade_price) %></td>
                  <td><%= trade.trade_datetime %></td>
                  <td><%= number_to_currency(trade.current_price) %></td>
                  <td><%= trade.change %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>

app/views/portfolios/_sidebar.html.erb
<div class="sidebar">
	<ul class="nav nav-pills nav-stacked">
		<li> <%= link_to 'Create Position', create_trade_path, :remote => true %> </li>
	</ul>
	<table class="table table-sidebar">
		<tbody>
			<tr>
				<td>Invested:</td>
				<td><%= number_to_currency(@portfolio.stock_value) %></td>
			</tr>
			<tr>
				<td>Cash:</td>
				<td><%= number_to_currency(@portfolio.portfolio_cash_account) %></td>
			</tr>
			<tr>
				<td class="tval-td-class">Total:</td>
				<td id="totalVal" class='tval-td-class'><%= number_to_currency(@portfolio.total_value) %></td>
			</tr>
		</tbody>
	</table>

</div>

app/views/portfolios/_update_position.html.erb
  <div id="updatePosition" class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 id="modalHeader" class="center">Update Position</h4>
      </div>
      <!-- @all_attribs and @header_attribs -->
      <div class="modal-body">
        <%= form_for @position, url: update_position_path, remote: true do |f| %>
          <table align="center" class="table table-striped table-bordered">
            <tbody class="center">
              
            </tbody>
          </table>
          <%= f.submit "Update", :id => "updatePositionBtn", class: "btn btn-primary" %> 
        <% end %>
      </div>
    </div>
  </div>

app/views/portfolios/load.html.erb
<% content_for :sidebar do %>
<!-- sidebar content -->

<% end %>

<div class ="portfolioDiv">

	<h1 class='center'><%= @user.user_name%></h1>

	<table class="table table-line">
		<tbody><tr><td></td></tr></tbody>
	</table>

	<table class="table table-bordered table-metrics">
		<thead>
			<tr>
				<th colspan="4"><h2>Key Stats</h2></td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Net Worth</td>
				<td class="td-middle-border">$100,000.00</td>
				<td>Buying Power</td>
				<td>$100,000.00</td>
			</tr>
			<tr>
				<td>Overall Gains</td>
				<td class="td-middle-border">$0.00</td>
				<td>Cash</td>
				<td>$100,000.00</td>
			</tr>
			<tr>
				<td>Returns</td>
				<td class="td-middle-border">%0.00</td>
				<td>Borrowed</td>
				<td>$0.00</td>
			</tr>
			<tr>
				<td>Todays Gains/Losses</td>
				<td class="td-middle-border">$0.00</td>
			</tr>
		</tbody>
	</table>

	<table class="table table-bordered">
		<thead>
			<tr>
				<th colspan="8">
					<h2>Holdings</h2>
				</th>
			</tr>
			<tr>
				<% @headers.each do | header | %>
					<td>
						<%= header %>
					</td>
				<% end %>
			</tr>
		</thead>
		<tbody>
			<% @position_stock.each do |position, stock| %>
				<tr id="<%=	stock.id %>">
					<td><%=	stock.stock_name %></td>
					<td><%= stock.sector %></td>
					<td><%= stock.industry %></td>
					<td><%=	stock.stock_symbol %></td>
					<td><%=	number_to_currency(stock.stock_price) %></td>
					<td><%= position.position_amount %></td>
					<td><%= number_to_currency(position.value) %></td>
					<td>
						<div class="center">
							<%= link_to position_history_path(:position_id => position.id), :remote => true, class: 'btn btn-primary' do %>
								<span>Trade History</span>
							<% end %>
						</div>
					</td>
				</tr>
			<% end	%>
		</tbody>
	</table>
	<div class="portfolio-history-container">
		<table align="center" class="table table-striped table-bordered table-headers-bold center portfolio-history-table">
		    <thead>
		    	<tr>
					<th colspan="6">
						<h2>Portfolio Trade History</h2>
					</th>
				</tr>
		      <tr>
		        <td>Transaction</td>
		        <td>Amount</td>
		        <td>Price</td>
		        <td>Date</td>
		        <td>Current Price</td>
		        <td>Change (%)</td>
		      </tr>
		    </thead>
		    <tbody class="center">
		      <% @trades.each do |trade| %>
		        <tr>
		          <td><%= trade.type %></td>
		          <td><%= trade.trade_amount %></td>
		          <td><%= number_to_currency(trade.trade_price) %></td>
		          <td><%= trade.trade_datetime %></td>
		          <td><%= number_to_currency(trade.current_price) %></td>
		          <td><%= trade.change %></td>
		        </tr>
		      <% end %>
		    </tbody>
	  </table>
	</div>
	

	<table class="table table-line">
		<tbody><tr><td></td></tr></tbody>
	</table>
	<br>

</div>

app/views/portfolios/portfolio_history.js.erb
$("#modal-window").html("<%= escape_javascript render(:partial => '/portfolios/portfolio_history') %>");
$('#modal-window').modal('show');

$(".button-submit").on('click', function() {
	$("#modal-window").modal('hide');
})

$('.modal ').insertAfter($('body'));

app/views/portfolios/position_history.js.erb
$("#modal-window").html("<%= escape_javascript render(:partial => '/portfolios/position_history') %>");
$('#modal-window').modal('show');

$(".button-submit").on('click', function() {
	$("#modal-window").modal('hide');
})

$('.modal ').insertAfter($('body'));

app/views/portfolios/update_position.js.erb
$("#modal-window").html("<%= escape_javascript render(:partial => '/portfolios/update_position') %>");
$('#modal-window').modal('show');

$(".button-submit").on('click', function() {
	$("#modal-window").modal('hide');
})

$('.modal ').insertAfter($('body'));