config/routes.rb
Rails.application.routes.draw do

  # Home Page
  root 'dangerous#landing_page'

  # User Routes

  get 'add_user' => 'users#add_user'
  get 'manage_user' => 'users#manage_user'
  get 'delete_user' => 'users#delete_user'
  patch 'manage_user' => 'users#edit_user'
  get 'manage_user_roles' => 'users#manage_roles'
  patch 'update_user_roles' => 'users#update_user_roles'

  # Resources
  resources :users
  resources :stocks
  resources :portfolios

  # path used by Register button
  post 'register_user' => 'users#create'

  # Session Routes
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get 'invalid_login' => 'dangerous#landing_page'

  # Portfolio Routes

  get 'portfolio' => 'portfolios#load'
  get 'position_history' => 'portfolios#position_history'
  get 'portfolio_history' => 'portfolios#portfolio_history'

  # Stock Routes

  get 'add_stock' => 'stocks#add_stock'
  get 'update_stock' => 'stocks#update_stock'
  post 'create_stock' => 'stocks#create'
  patch 'update_stock' => 'stocks#edit_stock'


  # Admin Routes

  get 'admin' => 'admin#manage_users'
  get 'manage_users' => 'admin#manage_users'
  get 'manage_stocks' => 'admin#manage_stocks'
  post 'admin_import' => 'admin#import'

  # Exchange Routes

  get 'exchange' => 'exchange#view'
  get 'create_trade' => 'exchange#create_trade'
  post 'create_trade' => 'exchange#execute_trade'
  post 'refresh_exchange' => 'exchange#refresh'


end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :user_name, uniqueness: true
	validates :email, uniqueness: true
	def add_role(role)
		# Create UTR 
		Rails.logger.info("SELF: " + self.id.to_s)
		Rails.logger.info("ROLE: " + role.id.to_s)
		UserToRole.create(user_id: self.id, role_id: role.id)
	end

	def has_role(role)
		return UserToRole.exists?(:user_id => self.id, :role_id => role.id)
	end

	def is_admin
		return true
	end

	def to_param
		user_name
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		# Profile page
		Rails.logger.info(params)
		@current_user = User.find(session[:user_id])
		if @user = User.find_by(user_name: params[:id]) then
			
			@is_admin = @current_user.is_admin
			@is_current_user = (@user.id == @current_user.id)
			@header_attribs = ['Username', 'Email', 'New Password']
			@all_attribs = ['user_name', 'email', 'password']
			

			# Find Portfolio for User


			@portfolio = Portfolio.find_by(user_id: @user.id)
		    @position_ids = Position.where(portfolio_id: @portfolio.id).select("id")
	    	@trades = Trade.where(position_id: @position_ids)
		else
			redirect_to user_path(:id => @current_user.user_name)
		end
		

		respond_to do |format|
			format.html {}
		end
	end

	def create
		@user = User.new(user_params)

		Rails.logger.info(@user)
		if @user.save
			# TODO: cache the user id for the session. 
			session[:user_id] = @user.id
			if params[:role] then
				@user.add_role(Role.find(params[:role]))
			else
				@user.add_role(Role.find_by(role_name: "ADMIN"))
			end
			
			Portfolio.create(portfolio_name: 'Portfolio', user_id: @user.id, portfolio_cash_account: 100000.00)
			# Need a logged-in landing page. 
			redirect_to user_path(:id => @user.user_name)
		else
			# Unsuccessful login. 
			Rails.logger.info(@user.errors.full_messages)

		end

		respond_to do |format|
			format.js {}
		end
	end

	def manage_user
		@user = User.find_by(user_name: params[:user_name])
		@header_attribs = ['Username', 'Email', 'New Password']
		@all_attribs = ['user_name', 'email', 'password']

		respond_to do |format|

			format.js {}

		end
	end

	def edit_user
		Rails.logger.info(user_params)
		@user = User.find(params[:user][:id])
		@user.update_attributes(user_params)

		respond_to do |format|
			format.js {}
		end
	end

	def manage_roles
		@user = User.find_by(user_name: params[:user_name])
		@roles = Role.all
		@user_roles_bool = [];
		@roles.each do |role|
			@user_roles_bool.push(@user.has_role(role))
		end

		@user_roles = @roles.zip(@user_roles_bool)

		Rails.logger.info(@user_roles)
		
		respond_to do |format|
			format.js {}
		end
	end

	def update_user_roles
		# params[:role_check] is the array of enabled roles. 
		role_checks = params[:role_check]

		if role_checks.empty? then
		else
			UserToRole.where(:user_id => params[:user_id]).destroy_all
			role_checks.each do |role_id|
				UserToRole.create(user_id: params[:user_id], role_id: role_id)
			end
		end
		respond_to do |format|
			format.js {}
		end

	end

	def update
	end

	# method to delete user. 
	def delete
		# How does the user id get here?

		User.find(params[:id]).destroy
		
	end

	def delete_user
		# delete the user, reload the table
		Rails.logger.debug(params[:user_name])
		User.find_by(user_name: params[:user_name]).destroy()
		respond_to do |format|
			format.js {}
		end
	end

	# launch modal for adding user. 
	def add_user
		@user = User.new 
		@header_attribs = ['Username', 'Email', 'Password']
		@all_attribs = ['user_name', 'email', 'password']
		respond_to do |format| 
			format.js {}
		end
	end


	private
		# Require/permit user_name|email|password for initial registration
		def user_params
			params.require(:user).permit(
				:id,
				:user_name, 
				:email,
				:password)
		end

	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_add_user.html.erb
  <div id="addUser" class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 id="modalHeader" class="center">Add User</h4>
      </div>
      <!-- @all_attribs and @header_attribs -->
      <div class="modal-body">
        <%= form_for @user, url: register_user_path, remote: true do |f| %>
          <table align="center" class="table table-striped table-bordered">
            <tbody class="center">
              <% @header_attribs.zip(@all_attribs).each do |header, attribute| %>
                <tr>
                  <td><%= header %></td> 
                  <td>
                    <%= f.text_field attribute, class: "form-control" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= f.submit "Add", :id => "addEquipmentBtn", class: "btn btn-primary" %> 
        <% end %>
      </div>
    </div>
  </div>

app/views/users/_adminnavbar.html.erb
<div class="row row-navbar">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="col-sm-2"></div>
      <div class="col-sm-8">
        <ul class="nav navbar-nav navbar-left">
          <li> <%= link_to 'NVESTR', portfolio_path(:id => current_user.user_name) %> </li>
        
          <li> <%= link_to 'Admin Dashboard', admin_path %> </li>
        
        <li> <%= link_to 'Exchange', exchange_path %> </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle"><b class="glyphicon glyphicon-question-sign"></b></a>
                <ul class="dropdown-menu nvestr-dropdown-menu">
                    <!-- Piopulate with help -->
                    <li> <%= link_to 'Help', user_path(:id => current_user.user_name) %> </li>
                    <li> <%= link_to 'About', portfolio_path(:id => current_user.user_name) %> </li>
                    <li> <%= link_to 'FAQ', portfolio_path(:id => current_user.user_name) %> </li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle"><b class="glyphicon glyphicon-globe"></b></a>
                <ul class="dropdown-menu nvestr-dropdown-menu">
                    <!-- Piopulate with notifications -->
                    <li> <%= link_to 'Notification', user_path(:id => current_user.user_name) %> </li>
                    <li> <%= link_to 'Notification', portfolio_path(:id => current_user.user_name) %> </li>
                    <li> <%= link_to 'Notification', portfolio_path(:id => current_user.user_name) %> </li>
                </ul>
            </li>
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle"><%= current_user.user_name %> <b class="caret"></b></a>
                <ul class="dropdown-menu nvestr-dropdown-menu">
                    <li> <%= link_to 'Profile', user_path(:id => current_user.user_name) %> </li>
                    <li> <%= link_to 'Portfolio', portfolio_path(:id => current_user.user_name) %> </li>
                    <li class="divider"></li>
                    <li> <%= link_to 'Log Out', logout_path(:user_id => current_user.id), method: "delete" %> </li>
                </ul>
            </li>
            
        </ul>
      </div>
      <div class="col-sm-2"></div>
        
    </div><!-- /.navbar-collapse -->
  </nav>
</div>

app/views/users/_manage_roles.html.erb
  <div id="manageUserRoles" class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 id="modalHeader" class="center">User Roles</h4>
      </div>
      <div class="modal-body">
          <table align="center" class="table table-striped table-bordered">
            <tbody class="center">
              <% @user_roles.each do |user_role| %>
                <tr>
                  <td><%= user_role[0].role_name %></td>
                  <td><%= check_box_tag(:test, value = "1", checked = user_role[1]) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>

app/views/users/_manage_user.html.erb
  <div id="manageUser" class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 id="modalHeader" class="center">Edit User Settings</h4>
      </div>
      <!-- @all_attribs and @header_attribs -->
      <div class="modal-body">
        <%= form_for @user, url: manage_user_path, remote: true do |f| %>
          <%=  f.hidden_field :id %>
          <table align="center" class="table table-striped table-bordered">
            <tbody class="center">
              <% @header_attribs.zip(@all_attribs).each do |header, attribute| %>
                <tr>
                  <td><%= header %></td> 
                  <td>
                    <%= f.text_field attribute, class: "form-control" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= f.submit "Update", :id => "addEquipmentBtn", class: "btn btn-primary" %> 
        <% end %>
      </div>
    </div>
  </div>

app/views/users/_usernavbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid half-width">
    <ul class="nav navbar-nav navbar-right">
      <li> <%= link_to 'Portfolio', logout_path, method: "delete" %> </li>
      <li> <%= link_to 'Account', logout_path, method: "delete" %> </li>
      <li> <%= link_to 'Log Out', logout_path, method: "delete" %> </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/users/add_user.js.erb
$("#modal-window").html("<%= escape_javascript render(:partial => '/users/add_user') %>");
$('#modal-window').modal('show');

$("#addUserModalBtn").on('click', function() {
	// Hide the modal. 
	$("#modal-window").modal('hide');
	// The table refresh needs to happen AFTER the database has been updated. 

})

app/views/users/create.js.erb
// Handle registration states. 
// States: U E P (so far)

// Clear all previous error messages

$("i[id='iconUsername:']").hide()
$("span[id='spanUsername:']").html("")

$("i[id='iconEmail:']").hide()
$("span[id='spanEmail:']").html("")

$("i[id='iconPassword:']").hide()
$("span[id='spanPassword:']").html("")
// Display errors
<% if @user.errors.full_messages.any? %>
  <% @user.errors.full_messages.each do |error_message| %>

   	console.log('<%= error_message %>')

   	<% if error_message.first == 'U' then %>
	// Username not available
		$("i[id='iconUsername:']").show()
		$("span[id='spanUsername:']").html('<%= error_message %>')
	<% elsif error_message.first == 'E' then %>
	// Email not available
		$("i[id='iconEmail:']").show()
		$("span[id='spanEmail:']").html('<%= error_message %>')
	<% elsif error_message.first == 'P' then %>
	// Password too short. 
		$("i[id='iconPassword:']").show()
		$("span[id='spanPassword:']").html('<%= error_message %>')
	<% end %>

  <% end %>
<% end %>

app/views/users/delete_user.js.erb
location.reload()

app/views/users/edit_user.js.erb
location.reload()

app/views/users/manage_roles.js.erb
$("#modal-window").html("<%= escape_javascript render(:partial => '/users/manage_roles') %>");
$('#modal-window').modal('show');

$('.btn-default').on('click', function() {
	// Hide the modal. 
	$("#modal-window").modal('hide');
	// The table refresh needs to happen AFTER the database has been updated. 

})

app/views/users/manage_user.js.erb
$("#modal-window").html("<%= escape_javascript render(:partial => '/users/manage_user') %>");
$('#modal-window').modal('show');

$("#manageUserModalBtn").on('click', function() {
	// Hide the modal. 
	$("#modal-window").modal('hide');
	// The table refresh needs to happen AFTER the database has been updated. 

})

app/views/users/show.html.erb
<div id="userProfile">
  	<div style="display:flex;">
	<div class="user-profile-avatar"></div>
	<div class="user-profile-info">
		<h3><%= @user.user_name %></h3>
		<h4><%= @user.email %></h4>
		<h4><%= link_to 'Portfolio', portfolio_path(:id => @user.user_name) %> </h4>
	</div>
  	</div>
  	<div style="width:100%; display: flex; margin-bottom: 20px;">
	  	<div class="user-profile-actions">
	  		<a href="#" class="icon user-profile-actions-btns">
	            <span class="glyphicon glyphicon glyphicon-plus"></span>
	        </a>
	  		<a href="#" class="icon user-profile-actions-btns" style="float: right;">
	            <span class="glyphicon glyphicon glyphicon-comment"></span>
	        </a>
	  	</div>
	  	<div class="user-profile-follow">
	  		<div>Followers: 1264</div>
	  		<div>Following: 145</div>
	  	</div>
	 </div>	
 	
    <!-- Nav tabs -->
	<ul class="nav nav-tabs" role="tablist">
		<li class="nav-item active">
	    	<a class="nav-link" data-toggle="tab" href="#posts" role="tab">Posts</a>
	  	</li>
	  <li class="nav-item">
	    <a class="nav-link" data-toggle="tab" href="#activity" role="tab">Activity</a>
	  </li>
	  <% if @is_admin then %>
	  <li class="nav-item">
	    <a class="nav-link" data-toggle="tab" href="#settings" role="tab">Edit Profile & Settings</a>
	  </li>
	  <% end %>
	</ul>
</div>

<!-- TODO: Add placeholders for:
	Avatar
	Username
	Email
	Website
	Follow
	Direct Message
	Blog Posts
	Portfolio Performance chart
	Timeline -->
<div class="tab-content">
	<div class="tab-pane active" id="posts" role="tabpanel">
		
		<% if @is_current_user then %>
			<div style="width:100%;">
				<%= text_field_tag 'title', nil, placeholder: 'Title', class: "form-blog form-blog-title" %>
			</div>
			<div style="width:100%;">
				<%= text_field_tag 'post', nil, placeholder: 'Tell your story:', class: "form-blog form-blog-post" %>
			</div>
	  	<% end %>

	  	<div id="postHistory">
	  	</div>

  		

  	</div>
	<div class="tab-pane" id="activity" role="tabpanel">
		<div style="width:75%; margin:auto; margin-top:20px;">
			<table align="center" class="table table-striped table-bordered table-headers-bold center">
            <thead>
              <tr>
                <td>Transaction</td>
                <td>Amount</td>
                <td>Price</td>
                <td>Date</td>
                <td>Current Price</td>
                <td>Change (%)</td>
              </tr>
            </thead>
            <tbody class="center">
              <% @trades.each do |trade| %>
                <tr>
                  <td><%= trade.type %></td>
                  <td><%= trade.trade_amount %></td>
                  <td><%= number_to_currency(trade.trade_price) %></td>
                  <td><%= trade.trade_datetime %></td>
                  <td><%= number_to_currency(trade.current_price) %></td>
                  <td><%= trade.change %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
		</div>
		
	</div>
	<% if @is_admin then %>
	  <div class="tab-pane" id="settings" role="tabpanel">
	  	<%= form_for @user, url: manage_user_path, remote: true do |f| %>
          <%=  f.hidden_field :id %>
          <div style="width:50%; margin:auto;" class="center">
          	<table align="center" class="table table-bordered table-edit-user">
	            <tbody class="center">
	              <% @header_attribs.zip(@all_attribs).each do |header, attribute| %>
	                <tr>
	                  <td><%= header %></td> 
	                  <td>
	                    <%= f.text_field attribute, class: "form-control" %>
	                  </td>
	                </tr>
	              <% end %>
	            </tbody>
	          </table>
          <%= f.submit "Update", :id => :id, class: "btn btn-primary user-update-btn" %> 
          </div>
          
        <% end %>
	  </div>
	<% end %>
</div>

app/views/users/update_user_roles.js.erb
$("#modal-window").modal('hide');